### ISSUE TITLE
Suggestion: Materials

### ISSUE THREAD

**Issue by PonyPhreak** [nosoop/SM-TFCWXBaseAttributes#13]
Is it possible to add compatibility with materials?  it  may allow warpaint application, and let custom models with a separate model/material directorys to work with this.  -- or potentially add in VKP compatibility?

**Comment by nosoop** [comment]
The material system is mostly handled on the client via shaders; there isn't anything that can be done on the server side to provide support for that (aside from maybe team colored / Botkiller variations that are already on the models).
