### ISSUE TITLE
(L4D2) Could you please take a look at the crash issues displayed in crash.limetech?

### ISSUE THREAD

**Issue by S4GAf** [nosoop/SM-TFCWXBaseAttributes#19]
Hello friends,

I am experiencing a server crash problem with the code '**CF4P-XOXX-5SE2**' on **crash.limetech.org**, and I can't figure out the reason behind it. I kindly request assistance from knowledgeable individuals. Thank you in advance.

---------------------------------------------------------

I am keeping these files in the "extensions" folder at the same time, but actually, only one server is focused on Left 4 Dead 2, while the others are random. Could they be causing any issues? Should I remove them? >

IMAGE : [https://ibb.co/BnqQV2z](https://ibb.co/BnqQV2z)

---------------------------------------------------------

Note: 

"left4dead2/addons/sourcemod/configs/geoip/GeoLite2-City.mmdb)
L 06/17/2023 - 19:34:28: [GEOIP] GeoIP2 supported languages: de en es fr ja pt-BR ru zh-CN
L 06/17/2023 - 19:34:28: [GEOIP] Your database is older than 90 days. You should consider downloading a newer version from e.g. https://dev.maxmind.com/geoip/geolite2-free-geolocation-data"

It says that GeoIP is older than 90 days, how can I update it? How can I refresh it?

I would like to thank my helpful friends in advance for their assistance.

**Comment by nosoop** [comment]
Hi &mdash; this is neither an L4D2 nor GeoIP-specific repository.

Please raise the issue in more appropriate support channels.
