### ISSUE TITLE
Hi &mdash; this is neither an L4D2 nor GeoIP-specific repository.

### ISSUE THREAD

**Issue by S4GAf** [nosoop/SM-TFCWXBaseAttributes#20]
Hi &mdash; this is neither an L4D2 nor GeoIP-specific repository.

Please raise the issue in more appropriate support channels.

_Originally posted by @nosoop in https://github.com/nosoop/SM-TFCWXBaseAttributes/issues/19#issuecomment-1595883318_

**Comment by S4GAf** [comment]
I am using GitHub for the first time. What is the appropriate channel? Where should I open the location?

Thank you.

**Comment by nosoop** [comment]
You may want to raise the issue at [the AlliedModders forum](https://forums.alliedmods.net/) or on [the AlliedModders Discord](https://discord.gg/HUc67zN).  Ideally you should first search the error phrase with Google or another search engine to see if other users have experienced the same issue.
