### ISSUE TITLE
Issues on "lighting-quirk-fix" build

### ISSUE THREAD

**Issue by ShadowMario** [nosoop/SM-TFCWXBaseAttributes#3]
Those issues as far as i've seen are basically the only downsides in using this version

1. Worldmodel of the original wepon isn't hidden unless you're taunting
![Screenshot_2](https://user-images.githubusercontent.com/44785097/117485268-90f8f500-af3e-11eb-9244-ab33af8310cf.png)

2. Update it with https://github.com/nosoop/SM-TFCWXBaseAttributes/issues/2

**Comment by nosoop** [comment]
Looks like the VScript update means the tradeoffs between proper lighting and third-person rendering hacks is no longer required.  Will look into migrating the attribute to use the official custom VM support.
