### ISSUE TITLE
View / worldmodels broken as of 2021-06-22 update

### ISSUE THREAD

**Issue by sticks-stuff** [nosoop/SM-TFCWXBaseAttributes#4]
Weapons are invisible

**Comment by nosoop** [comment]
Thank you for the report &mdash; have you [updated the gamedata for tf2utils](https://github.com/nosoop/SM-TFUtils/blob/master/gamedata/tf2.utils.nosoop.txt)?  The recent game update caused some function calls to not be where tf2utils expects them, and the viewmodel functionality depends on tf2utils to handle that.

This may be related to nosoop/SM-TFCustomWeaponsX#23.

**Comment by sticks-stuff** [comment]
Oops! I'm super sorry! Yep that fixed it, thank you!

**Comment by sticks-stuff** [comment]
Wait, nevermind lol. Updating the gamedata fixed sm_cwx_equip not working but it didn't fix invisible viewmodels. The worldmodel is correct however.
![image](https://user-images.githubusercontent.com/4157860/123506117-b42a6000-d6b6-11eb-843f-03360f2739bf.png)

**Comment by nosoop** [comment]
Interesting; I'll go ahead and reopen this.  Quick test on my machine seems like they both work as expected, but I've had a separate report sent privately so it doesn't seem to just be a one-off problem.

It uses the same wearable functionality as the shield equips, so they should either both work or not.

**Comment by chosenbill** [comment]
I thank noscoop linking me to this. I still use CW3 and my situation is similar but worse as in even the hands dont show up, but i also tried using https://forums.alliedmods.net/showthread.php?p=2742241#post2742241 which uses noscoop's Custom Attributes framework and that resulted in me getting same results as sticks-stuff.

**Comment by nosoop** [comment]
Yeah; I can't reproduce this issue at all with assets I have on hand &mdash; I can see custom viewmodels without issue on both Windows and Linux servers.

Attached is a CWX configuration with one all-class melee item with a stock replacement model; please test it and let me know whether or not you can see the item and if there are any error messages printed in server / client consoles.

[viewmodel_test_item.txt](https://github.com/nosoop/SM-TFCWXBaseAttributes/files/6720008/viewmodel_test_item.txt)

**Comment by chosenbill** [comment]
I dont really know where to put this as this is the first time I know about SM-TFCWXBaseAttributes, i have downloaded it just now. But could you please elaborate about what to do with the above? Bold attempt but I tried putting it in configs/customweapons, nothing happened.

**Comment by sticks-stuff** [comment]
This works but sometimes it turns red for whatever reason

![image](https://user-images.githubusercontent.com/4157860/123527230-ceedea80-d731-11eb-8e5e-9a9fd218a34e.png)
![image](https://user-images.githubusercontent.com/4157860/123527239-dad9ac80-d731-11eb-9201-731d1a397f52.png)

**Comment by nosoop** [comment]
Ah, yeah; the lighting issue affects the mainline branch (there's a `lighting-quirk-fix` branch which backports the fix from @Zabaniya001's plugin, but it has its own share of quirks).

Because the arm and weapon do show up, it looks like the wearable system and viewmodels work, so this shouldn't be an issue with the plugin itself.

It could be a change related to loading custom models; I did notice a few filesystem-related changes landed with the update.  Are the models on your system located under `tf/downloads/models`, or were they installed within `tf/custom` or `tf/models/`?  All of mine are in `tf/downloads/models`.

**Comment by sticks-stuff** [comment]
They're in `tf/downloads/models`

**Comment by chosenbill** [comment]
I had to run somewhere last time so had no time to explore things, however the module did work with cw3 still with the problem that sticks-stuff stated but I was having that before. If there is a fix for it that would be dope but I'm content with result either way.

**Comment by nosoop** [comment]
Are there still issues with viewmodels not displaying, @sticks-stuff? It looks like @chosenbill somehow managed to resolve the issue on their end.

I'm unfortunately still unable to reproduce this visibility on either the main or lighting-quirk-fix branches.

**Comment by sticks-stuff** [comment]
Yep, custom models still appear invisible for me, using the exact same settings as before the update when it was working

**Comment by sticks-stuff** [comment]
```
	"stick.SwordNormal"
	{
		// here's a condensed example
		"name"			"wii sports"
		"inherits"		"The Eyelander"
		"keep_static_attrs"		"0"
		"attributes_game"
		{
			"deploy time decreased" "0.005"
			"apply look velocity on damage" "100"
		}
		"attributes_custom"
		{
			"worldmodel override"	"models/wiisports/sword.mdl"
			"viewmodel override"	"models/wiisports/sword.mdl"
			"clientmodel override"	"models/wiisports/sword.mdl"
		}
	}
```

[wiisports_sword.zip](https://github.com/nosoop/SM-TFCWXBaseAttributes/files/6747278/wiisports_sword.zip)

**Comment by nosoop** [comment]
The model replacement test item indicates that the plugin is working as intended on your end, and I don't have any problems with the config or the model either.

That said, maybe remove `worldmodel override` and `viewmodel override`?  `clientmodel override` is intended a shortcut for both, but I'm not sure why they would conflict.  It does look like specifying `worldmodel override` alone causes viewmodels to be hidden; that may be a change that started with the update or something that was present before.

![20210702002414_1](https://user-images.githubusercontent.com/6760398/124237238-28586f80-dacc-11eb-900d-e192a83bf340.jpg)

**Comment by sticks-stuff** [comment]
Went back to this after months of abandoning this project, turns out I just forgot to add a crucial file to my downloads table… whoops…

Yeah, sorry about that, works perfectly now! Thank you very much for all your work on this project!

**Comment by nosoop** [comment]
Thanks for following up!  I'll add a note in the README indicating that the plugin doesn't perform any download table management in case someone else runs into a similar issue in the future.
