### ISSUE TITLE
Sniper's rifle occasionally disappears after zooming in

### ISSUE THREAD

**Issue by chosenbill** [nosoop/SM-TFCWXBaseAttributes#5]
As per the title, it could be fixed by simply switching weapons but still feels weird. An issue with CW3 at least. 

```
public void TF2_OnConditionRemoved(int client, TFCond cond)
{
	if(cond != TFCond_Taunting && TF2_GetPlayerClass(client) == TFClass_Sniper) UpdateClientWeaponModel(client);
}
```

This piece of code handles the issue.

_I don't encourage using CW3 anymore that CWX is out, but in case someone is using it for the time being like me._

**Comment by nosoop** [comment]
Thanks for the report.  Not sure what causes it, but having a check for this seems fine.
