### ISSUE TITLE
Demoman Sheild can't set custom model

### ISSUE THREAD

**Issue by gaejuck** [nosoop/SM-TFCWXBaseAttributes#8]
when I try to set it on the shield weapons, it doesn't properly work when equipped with grenade launchers, instead it just shows only in viewmodel.

	"{c00039}"
	{
		"name"	"Argent Shield"
		"item_class"	"tf_wearable_demoshield"
		"defindex"	"131"
		"keep_static_attrs"	"2"
		
		"used_by_classes"
		{
			"demoman" "secondary" 
		}

		"attributes_custom"
		{
			"clientmodel override"              "models/workshop/weapons/c_models/c_argent_shield/c_argent_shield.mdl"
			"worldmodel override"               "models/workshop/weapons/c_models/c_argent_shield/c_argent_shield.mdl"
			"viewmodel override"               	"models/workshop/weapons/c_models/c_argent_shield/c_argent_shield.mdl"
		}
	}

This is the custom model I used.
[argent_shield.zip](https://github.com/nosoop/SM-TFCWXBaseAttributes/files/7457977/argent_shield.zip)

**Comment by nosoop** [comment]
I suspect this one's probably fixed in the [`lighting-quirk-fix` branch](https://github.com/nosoop/SM-TFCWXBaseAttributes/commits/lighting-quirk-fix).  I'll look into merging the changes when I have the energy for it; will keep this issue open until then.

**Comment by nosoop** [comment]
If it's not fixed there, I suspect it might be fixed with the commit I just pushed (noticed some code comments indicating it's been an issue since 2021-06).  Apologies for the delay.

**Comment by nosoop** [comment]
Forgot to push the change.  It's definitely in aaf77d0495dac9da4921c010d8354f3d170b808e.
